using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Singleton ScriptableObject that owns every BlockDefinition and builds
/// the Texture2DArray used by the voxel material.
///
/// SETUP
/// ─────
/// Assets > Create > Voxel Void > Block Registry  (create one, keep only one)
///
/// 1. Add all your BlockDefinition assets to the `blocks` list.
/// 2. Click "Rebuild Registry" in the inspector (or call Rebuild() at runtime).
/// 3. Assign the generated `textureArray` to your voxel material's _MainTex slot.
///
/// TEXTURE ARRAY LAYOUT
/// ────────────────────
/// The array has (maxBlockId + 1) * 3 layers:
///   layer = blockId * 3 + faceSlot
///   faceSlot: 0 = top, 1 = bottom, 2 = side
///
/// This layout lets the NodeJob encode tex layer as a single ushort per face,
/// which the shader reads as:  texArray.Sample(sampler, float3(uv, layer))
///
/// RUNTIME LOOKUP
/// ──────────────
/// BlockRegistry.Instance.GetBlock(blockId)  — O(1) array lookup
/// BlockRegistry.Instance.IsAir(blockId)     — blockId == 0
/// </summary>
[CreateAssetMenu(menuName = "Voxel Void/Block Registry", fileName = "BlockRegistry")]
public class BlockRegistry : ScriptableObject
{
    // ------------------------------------------------------------------
    //  Singleton
    // ------------------------------------------------------------------

    private static BlockRegistry _instance;
    public static BlockRegistry Instance
    {
        get
        {
            if (_instance == null)
                _instance = Resources.Load<BlockRegistry>("BlockRegistry");
            return _instance;
        }
    }

    // ------------------------------------------------------------------
    //  Data
    // ------------------------------------------------------------------

    [Tooltip("All block definitions in the game. Order does not matter — blockId is the key.")]
    public List<BlockDefinition> blocks = new List<BlockDefinition>();

    [Tooltip("Generated by Rebuild(). Saved as VoxelTextureArray.asset next to this registry.")]
    public Texture2DArray textureArray;

    [Tooltip("Resolution of each texture in the array. All textures must match this size.")]
    public int textureSize = 256;

    // ------------------------------------------------------------------
    //  Fast runtime lookup — populated by Rebuild()
    // ------------------------------------------------------------------

    // Index = blockId, value = BlockDefinition (null = Air or unknown)
    private BlockDefinition[] _byId;

    public bool IsReady => _byId != null;

    /// <summary>
    /// Returns the BlockDefinition for a blockId, or null for Air (0) / unknown.
    /// Always O(1).
    /// </summary>
    public BlockDefinition GetBlock(byte blockId)
    {
        if (_byId == null) BuildLookup();
        if (blockId == 0 || blockId >= _byId.Length) return null;
        return _byId[blockId];
    }

    public bool IsAir(byte blockId) => blockId == 0;

    // ------------------------------------------------------------------
    //  Initialisation
    // ------------------------------------------------------------------

    private void OnEnable() => BuildLookup();

    private void BuildLookup()
    {
        if (blocks == null || blocks.Count == 0) return;

        int maxId = 0;
        foreach (var b in blocks)
            if (b != null && b.blockId > maxId) maxId = b.blockId;

        _byId = new BlockDefinition[maxId + 1];
        foreach (var b in blocks)
            if (b != null) _byId[b.blockId] = b;
    }

    // ------------------------------------------------------------------
    //  Texture array builder  (called from editor button or at startup)
    // ------------------------------------------------------------------

    /// <summary>
    /// Builds the Texture2DArray from all registered block textures and
    /// writes the tex array layer indices back into each BlockDefinition.
    ///
    /// Call this whenever you add a new block or change a texture.
    /// In the editor: use the "Rebuild Registry" button (BlockRegistryEditor).
    /// At runtime: called automatically in Awake if textureArray is null.
    /// </summary>
    public void Rebuild()
    {
        BuildLookup();
        if (_byId == null) return;

        int layerCount = (_byId.Length) * 3; // blockId * 3 + faceSlot

        // No mipChain — pixel art textures look correct without mipmaps.
        // Point filter is set after Apply() for crisp pixel art rendering.
        var arr = new Texture2DArray(textureSize, textureSize, layerCount,
            TextureFormat.RGBA32, mipChain: false, linear: false);
        arr.name = "VoxelTextureArray";

        for (int id = 1; id < _byId.Length; id++)
        {
            var block = _byId[id];
            if (block == null) continue;

            int layerTop = id * 3 + 0;
            int layerBottom = id * 3 + 1;
            int layerSide = id * 3 + 2;

            // Fallback: if side/bottom are null, copy top texture pixels directly
            Texture2D srcTop = block.topTexture;
            Texture2D srcBottom = block.bottomTexture != null ? block.bottomTexture : srcTop;
            Texture2D srcSide = block.sideTexture != null ? block.sideTexture : srcTop;

            CopyTexture(srcTop, arr, layerTop);
            CopyTexture(srcBottom, arr, layerBottom);
            CopyTexture(srcSide, arr, layerSide);

            block.texArrayLayerTop = layerTop;
            block.texArrayLayerBottom = layerBottom;
            block.texArrayLayerSide = layerSide;

#if UNITY_EDITOR
            UnityEditor.EditorUtility.SetDirty(block);
#endif
        }

        arr.Apply(updateMipmaps: false, makeNoLongerReadable: false);
        arr.filterMode = FilterMode.Point;   // crisp pixel art — no bilinear blur
        arr.wrapMode = TextureWrapMode.Repeat;
        textureArray = arr;

#if UNITY_EDITOR
        // Save the Texture2DArray as a .asset file on disk so it appears
        // in the Project window and can be referenced by the voxel material.
        string registryPath = UnityEditor.AssetDatabase.GetAssetPath(this);
        string dir = System.IO.Path.GetDirectoryName(registryPath);
        string arrayPath = System.IO.Path.Combine(dir, "VoxelTextureArray.asset");
        arrayPath = arrayPath.Replace("\\", "/");

        var existing = UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2DArray>(arrayPath);
        if (existing != null)
        {
            // Overwrite pixels into the existing asset so material references survive
            UnityEditor.EditorUtility.CopySerialized(arr, existing);
            textureArray = existing;
        }
        else
        {
            UnityEditor.AssetDatabase.CreateAsset(arr, arrayPath);
            textureArray = UnityEditor.AssetDatabase.LoadAssetAtPath<Texture2DArray>(arrayPath);
        }

        UnityEditor.EditorUtility.SetDirty(this);
        UnityEditor.AssetDatabase.SaveAssets();
        UnityEditor.AssetDatabase.Refresh();
        Debug.Log($"[BlockRegistry] Rebuilt → {arrayPath}  ({layerCount} layers, {textureSize}px)");
#endif
    }

    // ------------------------------------------------------------------

    private void CopyTexture(Texture2D src, Texture2DArray dst, int layer)
    {
        if (src == null)
        {
            // Fill with magenta so missing textures are obvious in-game
            var pixels = new Color32[textureSize * textureSize];
            for (int i = 0; i < pixels.Length; i++)
                pixels[i] = new Color32(255, 0, 255, 255);
            dst.SetPixels32(pixels, layer);
            return;
        }

        Color32[] srcPixels;

        if (src.width == textureSize && src.height == textureSize)
        {
            // Same size — copy directly
            srcPixels = src.GetPixels32();
        }
        else
        {
            // Resize by nearest-neighbour (preserves pixel art look)
            Debug.LogWarning($"[BlockRegistry] Texture '{src.name}' is {src.width}×{src.height}, " +
                             $"expected {textureSize}×{textureSize}. Resampling with nearest-neighbour.");
            var original = src.GetPixels32();
            srcPixels = new Color32[textureSize * textureSize];
            for (int y = 0; y < textureSize; y++)
                for (int x = 0; x < textureSize; x++)
                {
                    int sx = Mathf.Clamp(x * src.width / textureSize, 0, src.width - 1);
                    int sy = Mathf.Clamp(y * src.height / textureSize, 0, src.height - 1);
                    srcPixels[y * textureSize + x] = original[sy * src.width + sx];
                }
        }

        dst.SetPixels32(srcPixels, layer);
    }
}